# Use new trusty images, should yield newer compilers and packages
# ref: https://github.com/genbattle/dkm.git
sudo: required
dist: Rtrusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.4
      env: COMPILER=g++-4.4
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.6
      env: COMPILER=g++-4.6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-4.8
      env: COMPILER=g++-4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-all-dev
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - libboost-all-dev
            - clang-3.5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - libboost-all-dev
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - libboost-all-dev
            - clang-3.7
      env: COMPILER=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - libboost-all-dev
            - clang-3.8
      env: COMPILER=clang++-3.8

before_script: 
  - chmod +x ./bin/ci/before_install.sh
  - ./bin/ci/before_install.sh
script: 
  - chmod +x ./bin/ci/script.sh
  - ./bin/ci/script.sh
  
